### ISSUE TITLE
[Data] More Bus Statistics

### ISSUE THREAD

**Issue by dcjohnson24** [chihacknight/chn-ghost-buses#54]
Calculate some additional [bus statistics](https://activetrans.org/bus_routes/9-ashland) such as 

- Average speed
- Bunching
- Average headway
- Excess wait time (Actual headway - Scheduled headway)

These numbers could also be calculated for different sections of each route.

See [here](https://docs.google.com/document/d/1ELA5aQU_YPdlurSm1j51xGcHvocmP5yATZz4tspw5i8/edit) for more information.

**Comment by kollerbud** [comment]
are these issues still active and need to to be worked on?  I can start on them.

**Comment by dcjohnson24** [comment]
Yes these are still active. Thanks for your help.

**Comment by kristenhahn** [comment]
I may be able to help with some of this.  I've been working on headways using the chi-hack-night ghost buses data for awhile now [here](https://github.com/kristenhahn/cta_bus_tracker_exploration).  You're welcome to use anything you find helpful there, and I'm happy to help wherever I can.  A [jupyter notebook](all_headways_all_stops_single_route.ipynb) gives an overview of what the code in  [headways.py](https://github.com/kristenhahn/cta_bus_tracker_exploration/blob/main/headways.py) can do.  It calculates bus arrival times for a given bus stop, route, and direction of travel.  It calculates scheduled headways and actual headways and summarizes both.  Mean, median, 25th and 75th percentile headways are provided for the day at each bus stop on a given day and route.  This is an independent learning exercise for me, I'm not a professional coder.  So I think the logic is good, but I have no idea whether the code is clear and useful to others.  If not, comments or suggestions are always welcome.  I plan to add to the readme later this weekend, to explain a few nuances in the approach.

**Comment by dcjohnson24** [comment]
This looks great, thanks! I'll try to take a closer look at this later this week.
